services:
  - type: web
    name: science-dictionary
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: science-db
          property: connectionString

databases:
  - name: science-db
    plan: free
